In [17]:
import tensorflow as tf
# import tensorflow_io as tfio
import numpy as np


In [3]:
x = tf.constant(
    [
        [1.,2.,3.,],
        [4.,5.,6.,]
    ]
)

In [7]:
x @ tf.transpose(x)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

In [ ]:
tf.keras.layers.Dense()

In [18]:
audio = tf.random.normal([3,9152])

In [19]:
audio

<tf.Tensor: shape=(3, 9152), dtype=float32, numpy=
array([[-1.1441374 , -0.16269967, -0.60288286, ...,  1.4515191 ,
         0.2933324 ,  0.3342464 ],
       [-0.4407681 ,  0.55721277, -0.45458847, ..., -0.6515027 ,
        -0.09962724,  0.6606897 ],
       [-0.25754538,  2.4003565 ,  0.01341774, ..., -0.54135025,
         0.14615609,  0.22613885]], dtype=float32)>

In [20]:
frames = tf.signal.frame(audio, 512, 180)

In [21]:
frames

<tf.Tensor: shape=(3, 49, 512), dtype=float32, numpy=
array([[[-1.1441374 , -0.16269967, -0.60288286, ..., -0.54998654,
          0.6314353 , -0.5963412 ],
        [ 1.3512747 ,  0.45674783, -0.68506354, ...,  0.63979185,
         -0.71479064, -0.38490787],
        [ 0.22327599, -0.0636017 ,  1.1675197 , ..., -2.3027992 ,
         -0.4689477 , -1.337452  ],
        ...,
        [ 0.37291276, -0.2185477 ,  0.3788583 , ..., -0.3387708 ,
          0.5602863 , -0.24807116],
        [-0.89369786, -0.175412  , -1.768762  , ...,  0.4646627 ,
          0.23403631,  1.5711039 ],
        [ 0.5362503 , -0.2551124 ,  0.57325363, ...,  1.4515191 ,
          0.2933324 ,  0.3342464 ]],

       [[-0.4407681 ,  0.55721277, -0.45458847, ..., -1.1514759 ,
          0.92753744,  0.74209845],
        [-0.39880803,  1.9661865 , -2.0897918 , ...,  0.5041789 ,
          1.5986937 , -1.7675714 ],
        [-0.33845186,  1.5710562 , -0.67393744, ..., -1.1818653 ,
          0.9576815 , -1.3228674 ],
        ...,


In [16]:
a = [1,2,3,4]
mult = 1
for num in a:
    mult *= num
mult

24